name:                scratch
version:             0.1.0.0
github:              "philallen117/scratch"
license:             BSD3
author:              "Phil Allen"
maintainer:          "phil.allen.gm@gmail.com"
copyright:           "Phil Allen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/philallen117/scratch#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
#- quickcheck >= 2.9.2

library:
  source-dirs: src

executables:
  scratch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scratch

tests:
  scratch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scratch
